# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd21ccd4c055de9641c9475b8c5436007950a5b73441de25d0d8aa70e98291e000d88d8d3fb7b1eccef0baabd7323353775cbf8f4c04f6ef182fcc69c1381be8

test:
  secret_key_base: 8f896e8e1d41543139dd7ce1128039e4af578b2fccb0cbe625d555eec1669921b3587edca5934adba828252ea3697be36070d3ad035a064e6af6f78e77c38a7c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
